### ISSUE TITLE
Add reference to resource - firsttimersonly

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#20]
https://github.com/shanselman/firsttimersonly
![image](https://user-images.githubusercontent.com/876146/179426554-1bb10f89-e80d-4335-b7b4-1266c0aeb393.png)

https://www.firsttimersonly.com/

**Comment by CodeWAdi** [comment]
can you explain me what i have to do

**Comment by zo0o0ot** [comment]
This repo is the source code for a static site, written using [Hugo](https://gohugo.io/) and Markdown.
Instead of installing the framework, I set up the repo to run in [Gitpod](https://www.gitpod.io/).

What you'll want to do:

Option 1: Change inside of Gitpod and preview the changes

- Make a fork of this repo to your local user.
- Sign up for a free Gitpod account.  You can use your GitHub user to sign in.
- Open your fork in Gitpod (it may be useful to install the Gitpod extension for your browser for this.
-- The URL to open will look something like https://gitpod.io/#https://github.com/yourusername/howto-blog
![image](https://user-images.githubusercontent.com/876146/190049603-7805307f-eba5-4c9b-85e5-7103a633fb69.png)

- Open the howto-blog/blob/main/content/_index.md file.
- Look near the bottom of the file. Look near here:
 https://github.com/hacktoberfesthowto/howto-blog/blob/f5e578a7c8689435f38756bf2a98066d1406c1b6/content/_index.md?plain=1#L115-L123
- Also, open up howto-blog/blob/main/content/howto.md (some of the content is duplicated right now)
https://github.com/hacktoberfesthowto/howto-blog/blob/f5e578a7c8689435f38756bf2a98066d1406c1b6/content/howto.md?plain=1#L105-L113
- The information you need is inside [https://www.firsttimersonly.com/](https://www.firsttimersonly.com/)
- You should add a sentence with a link to [https://www.firsttimersonly.com/](https://www.firsttimersonly.com/) as an additional resource for first-timers and noobs.
- Provide a link to [https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions) for folks that are looking for a tutorial on a first contribution.
- Also, add some new links for good first issues, such as:
- [https://goodfirstissue.dev/](https://goodfirstissue.dev/)
- [https://goodfirstissues.com/](https://goodfirstissues.com/)
- You should be able to see a preview of this inside of Gitpod.
- Commit the changes and create a pull request.


Option 2: Make the change directly in GitHub.
- Make a fork of this repo to your local user.
- Download the two images that are attached to this GitHub issue.
- Upload the files to your fork, in the appropriate folder, like this: 
![image](https://user-images.githubusercontent.com/876146/190046400-81d4b0cd-4f3e-45e1-9bdf-820a1ea26728.png)
- Go to the howto-blog/blob/main/content/_index.md file. Click the pen to edit the file, or press"." to open Visual Studio Code inside the web browser.
- Look near here:
 https://github.com/hacktoberfesthowto/howto-blog/blob/f5e578a7c8689435f38756bf2a98066d1406c1b6/content/_index.md?plain=1#L115-L123
- Also, open up howto-blog/blob/main/content/howto.md (some of the content is duplicated right now)
https://github.com/hacktoberfesthowto/howto-blog/blob/f5e578a7c8689435f38756bf2a98066d1406c1b6/content/howto.md?plain=1#L105-L113
- The information you need is inside [https://www.firsttimersonly.com/](https://www.firsttimersonly.com/)
- You should add a sentence with a link to [https://www.firsttimersonly.com/](https://www.firsttimersonly.com/) as an additional resource for first-timers and noobs.
- Provide a link to [https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions) for folks that are looking for a tutorial on a first contribution.
- Also, add some new links for good first issues, such as:
- [https://goodfirstissue.dev/](https://goodfirstissue.dev/)
- [https://goodfirstissues.com/](https://goodfirstissues.com/)
- You should be able to see a preview of this inside of Gitpod.
- Commit the changes and create a pull request.


Once you have opened a pull request, we'll go from there!

**Comment by yashkhandelwal2203** [comment]
I have requested a pull request for the given task. Kindly check if it is correct or not.

**Comment by zo0o0ot** [comment]
Everything looks great! This issue was resolved in #29 .
