### ISSUE TITLE
Split HOWTO into contributor and maintainer sections

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#31]
### Main goals of this ticket:

With this issue, the site has two issues that I'd like to fix.

- The _index.md and howto.md files have a lot of duplicated content, and it would be preferable if the main page of the website wasn't the same as another page on the site.
- The howto.md post is a bit long and has content for two separate groups of folks:
-- Maintainers (the folks with repositories that will get pull requests)
-- Contributors (the folks that will find repositories to contribute to and make pull requests and code contributions)

### Work that's already done:

I've created placeholder pages for the new content, once it is split into the two subjects:
- https://github.com/hacktoberfesthowto/howto-blog/blob/main/content/howto-contributors.md
- https://github.com/hacktoberfesthowto/howto-blog/blob/main/content/howto-maintainers.md

### Work to update the menu:
The menu will also need to be updated.
Here is how the normal desktop site menu appears:
![image](https://user-images.githubusercontent.com/876146/193493213-740227d6-aa99-44e3-97f4-9aabf6cb2381.png)

Here is the mobile/small screen menu
![image](https://user-images.githubusercontent.com/876146/193493252-2f2e4493-abd5-4d97-9b8e-f6d9fa2b5832.png)

Once we've updated the site, the menu should have these links:
* HOWTO - Contributors
* HOWTO - Maintainers
* Swag History

The menu is not in a markdown file.  It's actually in the config.toml file.
Here is the current menu:
https://github.com/hacktoberfesthowto/howto-blog/blob/fdb2884e77fd8105ef8aea566560764131ad92f3/config.toml#L64-L72

This toml will need to be updated with the new page links once they are ready for publishing.

### Items to accomplish to complete this issue:

- Split the content from howto.md into howto-contributors.md for contributors and howto-maintainers.md for maintainers
- Update _index.md to no longer be mostly a duplicate of howto.md and instead provide links to the new pages for contributors and maintainers
- Update config.toml to have links to the new howto-contributors.md and howto-maintainers.md pages.

**Comment by Satoshi-Sh** [comment]
Hi Ross, I want to try this issue too.

**Comment by zo0o0ot** [comment]
Cool! I have assigned the issue to you.
