### ISSUE TITLE
Warn folks about spam submissions

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#33]
There are measures to combat spam submissions, we should inform people about them, so they don't clog up repositories with low quality submissions (or create low-quality repositories).

I'm not sure if directly repeating the information is appropriate, but here's the link (these links often change from year to year):

https://hacktoberfest.com/participation/#spam

MEASURES TO REDUCE SPAM
SPAMMY PULL/MERGE REQUESTS WILL BE LABELED AS “SPAM.”
Maintainers: label spammy requests “spam” and close them. PR/MRs labeled “spam” won’t count toward Hacktoberfest. Contributors with 2+ spammy PR/MRs are disqualified.

PULL/MERGE REQUESTS MUST BE APPROVED BY A MAINTAINER.
Maintainers accept PR/MRs by merging them, labeling them “hacktoberfest-accepted,” or giving them an overall approving review. Accepted PR/MRs enter a 7-day review window, during which approval can be revoked by the maintainer or by our team.

BAD REPOSITORIES WILL BE EXCLUDED.
PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest. Remember: quantity is fun, quality is key.

Found a repository that you think doesn’t follow our values? [REPORT IT TO US AND WE’LL TAKE A LOOK](https://hacktoberfest.com/report/).

AVOID SUBMITTING LOW-QUALITY PULL/MERGE REQUESTS.
Hacktoberfest is about contributing meaningfully to open-source projects. Here are some examples of low-quality pull/merge requests that won’t count towards Hacktoberfest.

Automated pull/merge requests: scripted opening pull requests to remove whitespace, fix typos or optimize images.
Disruptive pull/merge requests: taking someone else’s branch/commits and making a pull request.
Anything that a project maintainer flags as spam.
Anything that looks like an attempt to duplicate your pull request count for October.
Multiple pull/merge requests for the same issue that are unnecessary -for example five PR/MRs to remove a stray whitespace is not.

**Comment by michaella23** [comment]
Could I add this warning to the CONTRIBUTING file?

**Comment by zo0o0ot** [comment]
This is from the 2024 Hacktoberfest page at https://hacktoberfest.com/participation/:

[spam] Your PR/MRs must not be spammy.
PR/MRs that are labeled with a label containing the word “spam” by maintainers will not be counted.

We use the Node.js RegEx engine with /\bspam\b/i to look for spam labels.
PR/MRs that also have the “hacktoberfest-accepted” label cannot be marked as spammy via a label.
PR/MRs that have been merged and do not have a label containing the word “invalid” cannot be marked as spammy via a label.
 

PR/MRs that our system detects as spammy will also not be counted.

Any user with two or more spammy PR/MRs will be disqualified.

**Comment by zo0o0ot** [comment]
The warning about PR quality should probably go before https://github.com/hacktoberfesthowto/howto-blog/blob/main/content/howto-contributors.md#looking-for-additional-swag but after the links in https://github.com/hacktoberfesthowto/howto-blog/blob/main/content/howto-contributors.md#looking-for-additional-swag

**Comment by zo0o0ot** [comment]
It could also go into the CONTRIBUTING, file, like @michaella23 mentioned earlier.

**Comment by zo0o0ot** [comment]
Fixed in #51
