### ISSUE TITLE
Add a picture of the 2022 t-shirt to the history page

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#36]
Here's my tweet about the shirt when I got mine:
https://twitter.com/rosslarsonWI/status/1614744106344783874

More shirt/swag tweets:
- https://twitter.com/colbyfayock/status/1614245266562994176
- https://twitter.com/sadeeq_ismaela/status/1657161030403862530
- https://twitter.com/nithindaniel_/status/1631936095666712576
- https://twitter.com/SidLais351/status/1628337816215367682
- https://twitter.com/jtimoransky/status/1628004480246599680
- https://twitter.com/farisfaikar_r/status/1625436784476975105
- https://twitter.com/andygrunwald/status/1624042582950006787

Here's my original photos:
![IMG_20230115_141358799](https://github.com/hacktoberfesthowto/howto-blog/assets/876146/892c2b6a-e163-4947-8d19-e493ad6f4991)
![IMG_20230115_141447537](https://github.com/hacktoberfesthowto/howto-blog/assets/876146/cee4744e-9ffb-41f9-9034-d732811d10a1)
If there are better pictures on the internet that have permissive licenses, we could use those.

Also try to find one of the 2022 logos if possible, like the one on [this page](https://blog.tooljet.com/hacktoberfest-2022/).

We could also mention the tree planting, which may have started in 2022, but I'm not 100% positive when the first year of tree planting happened.

# How to add these images to the blog:
- Fork the repository so that you can make changes.
- Open the repository in gitpod.  It should open up an already functioning development environment.
- The environment should look something like this:
![image](https://github.com/hacktoberfesthowto/howto-blog/assets/876146/6059cd0e-913c-4210-bb73-11b130ecf8a6)
- Download the images that are in this issue. 
- Change the names of the image files to something human readable, like 2022-shirt-and-stickers.jpg and 2022-shirt-back.jpg
- Upload the images into the /static/images directory, similar to the other images that are there, such as https://github.com/hacktoberfesthowto/howto-blog/blob/main/static/images/2021Shirt.jpg
- Make a link to the images, with a 1000 pixel width limit, similar to the other images on the page.
- Here's what the previous year's pictures look like in the source code:
https://github.com/hacktoberfesthowto/howto-blog/blob/153dadeb55ffaf5050703097847058f0ec0a8712/content/history.md?plain=1#L55-L61
- Verify that things look right in the preview window.  You may need to reload the "simple browser" preview to see your changes.
- Commit your changes, and open a pull request showing what you've changed.

**Comment by SimonVerhoeven** [comment]
There is no t-shirt this year: https://hacktoberfest.com/about/#digital-rewards

**Comment by zo0o0ot** [comment]
@SimonVerhoeven You're totally right.  I named this issue wrong.  I wanted to get the 2022 shirt posted, and note something about the shirt not being a thing any more.  I'll rename the issue.

**Comment by radturkin** [comment]
Hi Id like to be assigned to this issue, please.

**Comment by zo0o0ot** [comment]
Sounds good! I've assigned the issue to you.  Let me know if you have any questions.

**Comment by radturkin** [comment]
pull request submitted #43
