### ISSUE TITLE
Mention new 2023 reward of trees. Include reason for lack of t-shirts.

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#40]
Hacktoberfest currently has their reasoning listed on their site:
![image](https://github.com/hacktoberfesthowto/howto-blog/assets/876146/0f3563a3-d8e8-4b03-971a-b783141ca978)

Currently, this information is available at https://hacktoberfest.com/participation/#faq

Relevant text:

> [Rewards] Why isn’t there a t-shirt this year?

> As Hacktoberfest has grown, so have the logistical challenges associated with creating a reward. Unfortunately, it’s no longer feasible for us to provide a free t-shirt. Nevertheless, we still want participants to have a memorable experience and receive a special memento marking their participation and the year. Instead of a t-shirt reward, we’re partnering with Holopin and our sponsors to provide digital rewards, making global delivery much simpler. We believe this shift will allow Hacktoberfest to continue supporting and raising awareness for open-source projects worldwide for years to come.

However, the Hacktoberfest site tends to be updated yearly, so there isn't a guarantee that it will stay there. It would be nice to create a digital record of the explanation.

It would also be nice to include some information about the trees that are being planted, along with a link to the [Tree Nation Hacktoberfest Forest](https://tree-nation.com/profile/hacktoberfest).

Preferably, we would put this information after the 2022 information described in #36 .

This information should be near the end of the history.md page. It should be around here: 
https://github.com/hacktoberfesthowto/howto-blog/blob/153dadeb55ffaf5050703097847058f0ec0a8712/content/history.md?plain=1#L55-L61

**Comment by zo0o0ot** [comment]
Note: I'm aware that this isn't the first year that trees were a reward option. However, I'm not sure when the first year was.

**Comment by Yasir761** [comment]
I would like to work on this issue, can you please assign me this?

**Comment by zo0o0ot** [comment]
Welcome!  Feel free to give it a try.

**Comment by iotalex** [comment]
@zo0o0ot please assign the issue to me and I will submit a PR within 24 hours. I have the PR ready to go once I'm assigned issue #40. Thank you!

**Comment by zo0o0ot** [comment]
Cool.  Have fun!
