### ISSUE TITLE
No more free T-shirts from GitHub. Update references.

### ISSUE THREAD

**Issue by zo0o0ot** [hacktoberfesthowto/howto-blog#52]
Historically, free t-shirts were a big part of Hacktoberfest, but starting last year, they aren't officially a part of Hacktoberfest any more. We have updated the information in the history section:
https://github.com/hacktoberfesthowto/howto-blog/blob/0692ca915048ef16488ccd021c228a6133e89418/content/history.md?plain=1#L77

However, the rest of the site still includes some references to t-shirts, which can be confusing for new participants in Hacktoberfest who are not familiar with the history.

Searching the repo for the word "shirt" gives an overview of some places that need to be reviewed:
![image](https://github.com/user-attachments/assets/63920017-03b4-4175-b937-f14470f3a84e)

In the content folder, check out:
* _index.md
* howto.md
* howto-contributors.md
* howto-maintainers.md

Thanks!

**Comment by christina-ml** [comment]
I'd like to work on this. Can I be assigned to this issue?

**Comment by zo0o0ot** [comment]
Sure!

**Comment by zo0o0ot** [comment]
Fixed in #53
